name=input("ENter any name : ")
print(name.upper())
print(name.lower())
print(name.replace("r","P"))
print(name.replace("r","P").upper())
print(name.replace("r","P").lower())
print(name.replace("r","P").title())
print(name.title())
print(name.find('r'))
print("Length of the name is ",len(name))
print("Priya" in name)